const state={countries:[],rulers:[],scale:18,showGrid:true,range:"auto"};
const LEVEL_WIDTHS=[2.1,1.35,.9,.65];
const NS="http://www.w3.org/2000/svg";
const countries=[{id:"pl",name:"Polska",code:"PL",order:1},{id:"pt",name:"Portugalia",code:"PT",order:2},{id:"es",name:"Hiszpania",code:"ES",order:3}];
const rulers=[
{id:"1",countryId:"pl",name:"Andrzej Duda",role:"prezydent",level:1,start:"2015",end:"2025",notes:"Dane demonstracyjne."},
{id:"2",countryId:"pl",name:"Donald Tusk",role:"premier",level:2,start:"2023",end:"2026"},
{id:"3",countryId:"pl",name:"Mateusz Morawiecki",role:"premier",level:2,start:"2017",end:"2023"},
{id:"4",countryId:"pt",name:"Marcelo Rebelo de Sousa",role:"prezydent",level:1,start:"2016",end:"2026"},
{id:"5",countryId:"pt",name:"António Costa",role:"premier",level:2,start:"2015",end:"2024"},
{id:"6",countryId:"pt",name:"Luís Montenegro",role:"premier",level:2,start:"2024",end:"2026"},
{id:"7",countryId:"es",name:"Felipe VI",role:"król",level:1,start:"2014",end:"2026"},
{id:"8",countryId:"es",name:"Pedro Sánchez",role:"premier",level:2,start:"2018",end:"2026"}
];
function uid(){return (crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()))}
function parseDate(s,isEnd){if(!s)return new Date();s=String(s).trim();let m;if(/^[-+]?\d{1,6}$/.test(s)){const y=Number(s);return new Date(Date.UTC(y,isEnd?11:0,isEnd?31:1))}m=s.match(/^(\d{1,2})[\/-](\d{4})$/);if(m){const y=+m[2],mo=+m[1]-1;return new Date(Date.UTC(y,mo,isEnd?new Date(Date.UTC(y,mo+1,0)).getUTCDate():1))}m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(m)return new Date(Date.UTC(+m[3],+m[2]-1,+m[1]));m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(m)return new Date(Date.UTC(+m[1],+m[2]-1,+m[3]));return new Date(s)}
function yf(d){return d.getTime()/31557600000}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function bounds(){const ds=[];state.rulers.forEach(r=>{ds.push(parseDate(r.start,false),parseDate(r.end,true))});const now=new Date();let max=ds.length?new Date(Math.max(...ds)):now;let min=ds.length?new Date(Math.min(...ds)):new Date(now.getFullYear()-100,0,1);if(state.range!=="auto"){max=now;min=new Date(now.getFullYear()-Number(state.range),0,1)}const pad=365.25*24*60*60*1000;max=new Date(max.getTime()+pad);min=new Date(min.getTime()-pad);return{min,max}}
function render(){const b=bounds(),top=62,left=64,yearH=(yf(b.max)-yf(b.min))*state.scale,countryW=190,gap=18,width=left+state.countries.length*(countryW+gap)+30,height=top+yearH+40;const div=document.getElementById("diagram");div.innerHTML="";const svg=document.createElementNS(NS,"svg");svg.setAttribute("width",width);svg.setAttribute("height",height);svg.setAttribute("viewBox","0 0 "+width+" "+height);const bg=document.createElementNS(NS,"rect");bg.setAttribute("width",width);bg.setAttribute("height",height);bg.setAttribute("fill","#fff");svg.appendChild(bg);const yFor=d=>top+(yf(b.max)-yf(d))*state.scale;
// Oś czasu jest pionowa: rok maleje w dół, a wysokość klocka wynika wyłącznie z czasu rządów.
const timeHeight=(start,end)=>Math.max(2,yFor(end)-yFor(start));
if(state.showGrid){for(let y=Math.ceil(yf(b.min));y<=Math.floor(yf(b.max));y++){const yy=yFor(new Date(Date.UTC(y,0,1)));if(yy<top||yy>height-20)continue;const line=document.createElementNS(NS,"line");line.setAttribute("x1",0);line.setAttribute("x2",width);line.setAttribute("y1",yy);line.setAttribute("y2",yy);line.setAttribute("stroke",y%10===0?"#cfd5dd":"#e8ebef");line.setAttribute("stroke-width",y%10===0?"1.2":".7");svg.appendChild(line);const t=document.createElementNS(NS,"text");t.setAttribute("x",8);t.setAttribute("y",yy-3);t.setAttribute("font-size","11");t.setAttribute("fill","#6b7280");t.textContent=y;svg.appendChild(t)}}
state.countries.forEach((c,ci)=>{const x=left+ci*(countryW+gap),head=document.createElementNS(NS,"rect");head.setAttribute("x",x);head.setAttribute("y",10);head.setAttribute("width",countryW);head.setAttribute("height",40);head.setAttribute("rx",6);head.setAttribute("fill","#eef2f6");head.setAttribute("stroke","#c9d0d8");svg.appendChild(head);const ct=document.createElementNS(NS,"text");ct.setAttribute("x",x+countryW/2);ct.setAttribute("y",35);ct.setAttribute("text-anchor","middle");ct.setAttribute("font-size","14");ct.setAttribute("font-weight","700");ct.textContent=c.name;svg.appendChild(ct);
const rs=state.rulers.filter(r=>r.countryId===c.id);const unit=countryW/5;for(let level=1;level<=4;level++){const offsets=[0,LEVEL_WIDTHS[0],LEVEL_WIDTHS[0]+LEVEL_WIDTHS[1],LEVEL_WIDTHS[0]+LEVEL_WIDTHS[1]+LEVEL_WIDTHS[2]],laneX=x+offsets[level-1]*unit,laneW=LEVEL_WIDTHS[level-1]*unit,rr=rs.filter(r=>+r.level===level),slots=[];rr.forEach(r=>{const s=parseDate(r.start),e=parseDate(r.end,true);let slot=0;while(slots[slot]&&slots[slot].some(o=>o.s<e&&s<o.e))slot++;if(!slots[slot])slots[slot]=[];slots[slot].push({s,e,r});r._slot=slot});const slotCount=Math.max(1,slots.length);rr.forEach(r=>{const s=parseDate(r.start),e=parseDate(r.end,true),ry=yFor(s),rh=Math.max(5,yFor(e)-ry),rw=laneW/slotCount,rx=laneX+(r._slot||0)*rw+1,rect=document.createElementNS(NS,"rect");rect.setAttribute("x",rx);rect.setAttribute("y",ry);rect.setAttribute("width",Math.max(2,rw-2));rect.setAttribute("height",rh);rect.setAttribute("rx",3);rect.setAttribute("fill","hsl("+((ci*71+level*43)%360)+" 62% 78%)");rect.setAttribute("stroke","#59636f");rect.setAttribute("class","ruler-block");rect.addEventListener("click",()=>showDetails(r));svg.appendChild(rect);if(rh>24){const tx=document.createElementNS(NS,"text");tx.setAttribute("x",rx+rw/2);tx.setAttribute("y",ry+18);tx.setAttribute("text-anchor","middle");tx.setAttribute("font-size",Math.min(12,Math.max(8,rw/10)));tx.setAttribute("fill","#1e293b");tx.setAttribute("pointer-events","none");tx.textContent=r.name;svg.appendChild(tx)}})}
const border=document.createElementNS(NS,"rect");border.setAttribute("x",x);border.setAttribute("y",top);border.setAttribute("width",countryW);border.setAttribute("height",yearH);border.setAttribute("fill","none");border.setAttribute("stroke","#9da6b2");svg.appendChild(border)});
div.appendChild(svg);document.getElementById("countryCount").textContent=state.countries.length;document.getElementById("rulerCount").textContent=state.rulers.length;document.getElementById("scaleLabel").textContent="1 rok ≈ "+state.scale.toFixed(1)+" px"}
function showDetails(r){const c=state.countries.find(x=>x.id===r.countryId);document.getElementById("detailsContent").innerHTML="<h3>"+esc(r.name)+"</h3><div class='detail-row'><b>Państwo:</b> "+esc(c?.name||"")+"</div><div class='detail-row'><b>Rola:</b> "+esc(r.role||"—")+"</div><div class='detail-row'><b>Poziom:</b> "+r.level+"</div><div class='detail-row'><b>Okres:</b> "+esc(r.start)+" – "+esc(r.end||"dziś")+"</div>"+(r.notes?"<div class='detail-row'><b>Uwagi:</b><br>"+esc(r.notes)+"</div>":"");document.getElementById("detailsPanel").classList.remove("hidden")}
function addCountry(name,code){state.countries.push({id:uid(),name,code,order:state.countries.length+1});render()}
function addRuler(r){state.rulers.push({...r,id:uid(),level:+r.level});render()}
function splitCsv(t){const rows=[];let row=[],cell="",q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
async function loadSheet(url){const res=await fetch(url);if(!res.ok)throw Error("Nie udało się pobrać CSV");const rows=splitCsv(await res.text());const h=rows[0].map(x=>x.trim().toLowerCase());const get=(r,...ns)=>{for(const n of ns){const i=h.indexOf(n);if(i>=0)return r[i]||""}return""};const cs=[],rs=[],map=new Map();rows.slice(1).forEach((row,i)=>{const cn=get(row,"kraj","country","państwo");if(!cn)return;let id=map.get(cn);if(!id){id="c"+map.size;map.set(cn,id);cs.push({id,name:cn,code:"",order:cs.length+1})}const name=get(row,"władca","osoba","person","imię i nazwisko");if(name)rs.push({id:"s"+i,countryId:id,name,role:get(row,"funkcja","rola","role","stanowisko"),level:+get(row,"poziom","level")||1,start:get(row,"od","start","data od","start_date"),end:get(row,"do","end","data do","end_date"),notes:get(row,"uwagi","notes","opis")})});if(!rs.length)throw Error("Brak władców w CSV");state.countries=cs;state.rulers=rs;render()}
document.getElementById("addCountryBtn").onclick=()=>document.getElementById("countryDialog").showModal();
document.getElementById("addRulerBtn").onclick=()=>{document.getElementById("rulerCountry").innerHTML=state.countries.map(c=>"<option value='"+c.id+"'>"+esc(c.name)+"</option>").join("");document.getElementById("rulerDialog").showModal()};
document.getElementById("saveCountryBtn").onclick=e=>{e.preventDefault();const n=document.getElementById("countryName").value.trim();if(n){addCountry(n,document.getElementById("countryCode").value.trim());document.getElementById("countryDialog").close();document.getElementById("countryForm").reset()}};
document.getElementById("saveRulerBtn").onclick=e=>{e.preventDefault();const r={countryId:document.getElementById("rulerCountry").value,name:document.getElementById("rulerName").value.trim(),role:document.getElementById("rulerRole").value.trim(),level:document.getElementById("rulerLevel").value,start:document.getElementById("rulerStart").value.trim(),end:document.getElementById("rulerEnd").value.trim(),notes:document.getElementById("rulerNotes").value.trim()};if(r.name&&r.start){addRuler(r);document.getElementById("rulerDialog").close();document.getElementById("rulerForm").reset()}};
document.getElementById("settingsBtn").onclick=()=>{document.getElementById("sheetUrl").value=localStorage.getItem("wthSheetUrl")||"";document.getElementById("showGrid").checked=state.showGrid;document.getElementById("settingsDialog").showModal()};
document.getElementById("reloadSheetBtn").onclick=async e=>{e.preventDefault();const u=document.getElementById("sheetUrl").value.trim();state.showGrid=document.getElementById("showGrid").checked;if(!u){render();document.getElementById("settingsDialog").close();return}try{localStorage.setItem("wthSheetUrl",u);await loadSheet(u);document.getElementById("settingsDialog").close()}catch(err){alert("Błąd: "+err.message)}};
document.getElementById("showGrid").onchange=e=>{state.showGrid=e.target.checked;render()};document.getElementById("rangeSelect").onchange=e=>{state.range=e.target.value;render()};document.getElementById("zoomInBtn").onclick=()=>{state.scale=Math.min(100,state.scale*1.25);render()};document.getElementById("zoomOutBtn").onclick=()=>{state.scale=Math.max(3,state.scale/1.25);render()};document.getElementById("fitBtn").onclick=()=>{const v=document.getElementById("diagramViewport"),b=bounds(),span=yf(b.max)-yf(b.min);state.scale=Math.max(3,Math.min(60,(v.clientHeight-90)/span));render()};document.getElementById("closeDetails").onclick=()=>document.getElementById("detailsPanel").classList.add("hidden");window.addEventListener("resize",render);
state.countries=countries;state.rulers=rulers;render();